version: "3"
services:
    node-app:
        restart: always
        depends_on: 
            - predictor
        build: .
        ports:
            - "8080:8080"
        links: 
            - mongo-app 
            - predictor
    mongo-app:
        # container_name: mongo
        image: mongo:latest
        ports: 
            - '27017:27017'

    mongo-seed:
        build: './mongo-seed'
        links:
            - mongo-app

    predictor:
        restart: always
        depends_on: 
            - mongo-seed
        build: './flask predictor model'
        ports: 
            - "5000:5000"
        links:  
            - mongo-app
            - mongo-seed